### ISSUE TITLE
[NEW ICON] Cypress

### ISSUE THREAD

**Issue by josephburgess** [tandpfun/skill-icons#331] opened 2023-02-22 05:59 UTC
### Skill Name

Cypress

### Why?

Popular front end testing framework

### Reference Image

<img width="100" alt="image" src="https://user-images.githubusercontent.com/4661986/220535884-9f832dfb-0209-4670-8bfb-7d7067a8af7c.png">

**Comment by Sls0n** [comment] 2023-02-22 08:13
Duplicate of #232

**Comment by tandpfun** [comment] 2024-02-29 03:38
Added in e67133b!

**Closed by tandpfun** 2024-02-29 03:38 UTC
Labels: icon suggestion
