### ISSUE TITLE
[NEW ICON] Discord.js

### ISSUE THREAD

**Issue by 0xMukesh** [tandpfun/skill-icons#15] opened 2022-03-12 02:01 UTC
### Skill Name

Discord.js

### Why?

It is a really popular choice for making discord bots!

### Reference Image

![djs](https://user-images.githubusercontent.com/90365542/157999486-479e7390-018f-4392-bf45-8d931d482b09.png)

**Comment by ThatOneCalculator** [comment] 2022-03-12 02:08
Duplicate of #6 .

A library on its own is far too specific (not to mention djs is practically deprecated)

**Comment by ThatOneCalculator** [comment] 2022-03-12 02:41
@Kira272921 since you saw this, and hopefully understood my message, it'd probably be a good idea to close this issue :)

**Comment by tandpfun** [comment] 2022-03-12 02:43
DJS isn't practically deprecated, and it is a pretty widely-used framework. I'll think about it.

**Comment by Kira272921** [comment] 2022-03-12 02:43
> @Kira272921 since you saw this, and hopefully understood my message, it'd probably be a good idea to close this issue :)

Ohh.. sorry I forgot to close the issue 😅

**Comment by Kira272921** [comment] 2022-03-12 02:43
> DJS isn't practically deprecated, and it is a pretty widely-used framework. I'll think about it.

Thanks :D

**Comment by Kira272921** [comment] 2022-03-12 02:44
Discord.py is deprecated i guess, as far as I remember

**Comment by ThatOneCalculator** [comment] 2022-03-12 03:43
> DJS isn't practically deprecated, and it is a pretty widely-used framework. I'll think about it.

Didn't the creator say that they were gonna abandon it?

**Comment by tandpfun** [comment] 2022-03-12 03:43
That's Discord.py

**Comment by ThatOneCalculator** [comment] 2022-03-12 03:44
> That's Discord.py

Ah, gotcha. Either way, I feel like having #6 to encompass *all* Discord frameworks is probably a better idea, given if DJS is added, everyone will want their favorite lib added too.

**Comment by warengonzaga** [comment] 2022-03-12 06:22
I think we don't need to add Discord.js as JS alone skill is fine... fine-tuning JS skills will end up us being obligated to supply it all. Like @ThatOneCalculator said "Discord" icon can encompass all Discord frameworks.

**Comment by tandpfun** [comment] 2022-03-12 06:57
I don't think a discord logo fully encompasses this, but I'll consider this tomorrow.

**Comment by ThatOneCalculator** [comment] 2022-03-12 07:14
> I don't think a discord logo fully encompasses this, but I'll consider this tomorrow.

Fs. Also, I never said the Discord logo alone would encompass bot dev (they mightve misinterpreted my comment?)

**Comment by ThatOneCalculator** [comment] 2022-03-13 02:46
Given both Discord and DiscordBots are implemented, I think this issue should be closed.

**Comment by tandpfun** [comment] 2022-03-13 02:48
Because these are huge libraries (bigger than some frameworks we have listed) I'm going to consider it + some other popular libs but I'm not 100% sure

**Comment by tandpfun** [comment] 2024-02-29 03:37
Added in e67133b!

**Closed by tandpfun** 2024-02-29 03:37 UTC
Labels: icon suggestion, low priority
