### ISSUE TITLE
[NEW ICON] Postman

### ISSUE THREAD

**Issue by Pyr33x** [tandpfun/skill-icons#215] opened 2022-10-14 18:56 UTC
### Skill Name

Postman

### Why?

Postman is a api platform and used by many developers

### Reference Image

![Postman](https://user-images.githubusercontent.com/83529331/195920574-a390dc48-30e0-43bd-8d3e-b84b1a57aabc.png)

**Comment by sivelswhy** [comment] 2022-10-24 16:08
Duplicate of #114

**Closed** 2022-11-28 15:04 UTC
Labels: icon suggestion
