### ISSUE TITLE
[NEW ICON] Gmail

### ISSUE THREAD

**Issue by AazainKhan** [tandpfun/skill-icons#301] opened 2023-02-03 20:03 UTC
### Skill Name

Gmail

### Why?

For those that want to hyperlink their email in their contact me section. Since Instagram isn't a skill but its there, there should be Gmail.

### Reference Image

![Gmail_icon_(2020) svg](https://user-images.githubusercontent.com/43759637/216699472-1d59bd7f-6e23-4320-9af5-ea14af15d5bf.png)

**Comment by kuroji-fusky** [comment] 2023-02-17 08:41
Duplicate of #134; someone already requested Gmail.

**Comment by tandpfun** [comment] 2024-01-05 00:38
✅ Added in de91fca307a83d75fc5b1f6ce24540454acead41!

**Closed by tandpfun** 2024-01-05 00:38 UTC
Labels: icon suggestion
