### ISSUE TITLE
[NEW ICON] Gmail

### ISSUE THREAD

**Issue by aryakghosal** [tandpfun/skill-icons#317] opened 2023-02-17 07:33 UTC
### Skill Name

Gmail

### Why?

Gmail should be added because it is a free, user-friendly email service provided by Google that offers numerous features such as large storage, efficient spam filtering, easy integration with other Google services, and access across multiple devices.

### Reference Image

https://upload.wikimedia.org/wikipedia/commons/7/7e/Gmail_icon_%282020%29.svg

**Comment by kuroji-fusky** [comment] 2023-02-17 08:40
Someone already requested Gmail; duplicate of #301, #134, and #92

**Comment by tandpfun** [comment] 2024-01-05 00:38
✅ Added in de91fca307a83d75fc5b1f6ce24540454acead41!

**Closed by tandpfun** 2024-01-05 00:38 UTC
Labels: icon suggestion
