### ISSUE TITLE
[NEW ICON] AdonisJS

### ISSUE THREAD

**Issue by PedroHercules** [tandpfun/skill-icons#219] opened 2022-10-24 13:44 UTC
### Skill Name

AdonisJS

### Why?

With AdonisJS, we don't need to worry about configuration or project structure, but with business rules. As a result, we become more productive. AdonisJS is an alternative to NestJS. Also, it is quite similar to laravel.. And I'm really enjoying learning about it.

**Comment by sivelswhy** [comment] 2022-10-24 16:12
You might consider changing your issue name to `[NEW ICON] AdonisJS`

**Comment by sivelswhy** [comment] 2022-10-24 16:18
Also, a duplicate of #189

**Closed** 2023-02-02 06:07 UTC
Labels: icon suggestion
